'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UXL_Launcher.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property AccessLargeSVG_3D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AccessLargeSVG_3D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property AccessSmallSVG_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AccessSmallSVG_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fnil\fcharset2 Symbol;}}
        '''{\*\generator Riched20 10.0.14393}\viewkind4\uc1 
        '''\pard\sl240\slmult1\qc\b\f0\fs10\lang9\par
        '''
        '''\pard\sl276\slmult1\qc\fs32 UXL Launcher Acknowledgements\b0\par
        '''
        '''\pard\sl360\slmult1\fs24\par
        '''
        '''\pard{\pntext\f1\&apos;B7\tab}{\*\pn\pnlvlblt\pnf1\pnindent0{\pntxtb\&apos;B7}}\fi-360\li720\sl360\slmult1 Original idea: God\par
        '''{\pntext\f1\&apos;B7\tab}Moral support: My mom, Nana, Mitty, and all my friend [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property Acknowledgements_RTF() As String
            Get
                Return ResourceManager.GetString("Acknowledgements_RTF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to applauncher-icons
        '''By Drew Naylor. Licensed under CC BY 4.0.
        '''Version 3.0
        '''
        '''The applauncher-icons project provides most of the icons used in UXL Launcher, with the exception of some icons. These include, but are not limited to, the UXL Launcher logo and the About window banner.
        '''
        '''Link to applauncher-icons project repository:
        '''https://github.com/DrewNaylor/applauncher-icons
        '''
        '''Link to applauncher-icons version 3.0 GitHub Releases page:
        '''https://github.com/DrewNaylor/applauncher-icons/releases/tag/v3.0
        '''
        '''T [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property ApplauncherIconsInfo_TXT() As String
            Get
                Return ResourceManager.GetString("ApplauncherIconsInfo_TXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  - Codename &quot;Burdened No Longer&quot;.
        '''</summary>
        Public ReadOnly Property appVersionCodename() As String
            Get
                Return ResourceManager.GetString("appVersionCodename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2021-06-06T12:04:52
        '''.
        '''</summary>
        Public ReadOnly Property BuildDate() As String
            Get
                Return ResourceManager.GetString("BuildDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Clip_Organizer_75x64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Clip_Organizer_75x64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DARK_UXL_Launcher_Banner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DARK_UXL_Launcher_Banner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maudern,ProDark,TenDark.
        '''</summary>
        Public ReadOnly Property darkthemesList() As String
            Get
                Return ResourceManager.GetString("darkthemesList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;UXL_Launcher_Theme&gt;
        '''  &lt;Title&gt;Default Theme&lt;/Title&gt;
        '''  &lt;Description&gt;Default is the theme UXL Launcher ships with.&lt;/Description&gt;
        '''  &lt;Version&gt;v1.2&lt;/Version&gt;
        '''  &lt;Author&gt;Drew Naylor&lt;/Author&gt;
        '''
        '''  &lt;!-- &quot;UseThemeEngineVersion&quot; is used to specify the version of the
        '''  UXL Launcher Theme Engine to use in case there are changes in newer
        '''  versions of the theme engine that designers or developers don&apos;t want
        '''  to use. Version 1.01 is the oldest version number available and anything
        '''  smaller than that will automat [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property DefaultTheme_XML() As String
            Get
                Return ResourceManager.GetString("DefaultTheme_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ExcelLargeSVG_3D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExcelLargeSVG_3D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ExcelNewWorksheet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExcelNewWorksheet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ExcelSmallSVG_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExcelSmallSVG_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;UXL_Launcher_Theme&gt;
        '''  &lt;Title&gt;Eyesore 2&lt;/Title&gt;
        '''  &lt;Description&gt;Originally a test theme for UXL Launcher, Eyesore 2 is meant to be a spiritual successor to the Windows 3.1 Hotdog Stand theme, but worse.&lt;/Description&gt;
        '''  &lt;Version&gt;v1.2&lt;/Version&gt;
        '''  &lt;Author&gt;Drew Naylor&lt;/Author&gt;
        '''
        '''  &lt;!-- &quot;UseThemeEngineVersion&quot; is used to specify the version of the
        '''  UXL Launcher Theme Engine to use in case there are changes in newer
        '''  versions of the theme engine that designers or developers don&apos;t want
        '''  to use. Version 1 [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property Eyesore2Theme_XML() As String
            Get
                Return ResourceManager.GetString("Eyesore2Theme_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;UXL_Launcher_Theme&gt;
        '''  &lt;Title&gt;Eyesore&lt;/Title&gt;
        '''  &lt;Description&gt;Eyesore is a theme that&apos;s meant to be a tribute to Windows 3.1&apos;s Hot Dog Stand theme. The &quot;Eyesore&quot; theme and Drew Naylor are not associated with Microsoft Corporation in any way, shape, or form. Windows 3.1 and all related words are copyright and trademark/registered trademark Microsoft Corporation in the United States and other countries. All rights reserved to Microsoft Corp. for Microsoft Corp.&apos;s copyrights and trademarks/registered trademar [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property EyesoreTheme_XML() As String
            Get
                Return ResourceManager.GetString("EyesoreTheme_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fswiss Helvetica;}{\f1\fswiss\fcharset0 Helvetica;}{\f2\fnil Courier;}}
        '''{\colortbl ;\red0\green0\blue255;}
        '''{\*\generator Riched20 10.0.14393}\viewkind4\uc1 
        '''\pard\sa180\b\f0\fs28\lang9 GNU GENERAL PUBLIC LICENSE\par
        '''\b0\fs24 Version 3, 29 June 2007\par
        '''Copyright \f1\&apos;a9 2007 Free Software Foundation, Inc. &lt;{{\field{\*\fldinst{HYPERLINK &quot;http://fsf.org/&quot;}}{\fldrslt{http://fsf.org/\ul0\cf0}}}}\f1\fs24 &gt;\par
        '''\f0 Everyone is permitted to copy and distribute verbat [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property gpl_RTF() As String
            Get
                Return ResourceManager.GetString("gpl_RTF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property InfopathLargeSVG_3D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InfopathLargeSVG_3D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property InfopathSmallSVG_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InfopathSmallSVG_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dev.
        '''</summary>
        Public ReadOnly Property isStable() As String
            Get
                Return ResourceManager.GetString("isStable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Language_Settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Language_Settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to libscrollswitchtabs
        '''Copyright (C) 2020 Drew Naylor. Licensed under Apache License 2.0.
        '''Version 0.1
        '''
        '''libscrollswitchtabs allows you to switch tabs in the Windows Forms TabControl using the mouse scroll wheel, like many Linux applications.
        '''
        '''libscrollswitchtabs is part of the drews-libs project.
        '''Link to drews-libs project repository:
        '''https://github.com/DrewNaylor/drews-libs
        '''
        '''
        '''No warranty is provided with libscrollswitchtabs. Use at your own risk. Drew Naylor is not responsible for any problems that  [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property libscrollswitchtabs_TXT() As String
            Get
                Return ResourceManager.GetString("libscrollswitchtabs_TXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;UXL_Launcher_Theme&gt;
        '''  &lt;Title&gt;Maudern Classic&lt;/Title&gt;
        '''  &lt;Description&gt;Maudern Classic is basically Maudern v1.0 plus a few extra things supported in TE1.03, in case anyone preferred that version&apos;s general appearance over Maudern v1.1.&lt;/Description&gt;
        '''  &lt;Version&gt;v1.1&lt;/Version&gt;
        '''  &lt;Author&gt;Drew Naylor&lt;/Author&gt;
        '''
        '''  &lt;!-- &quot;UseThemeEngineVersion&quot; is used to specify the version of the
        '''  UXL Launcher Theme Engine to use in case there are changes in newer
        '''  versions of the theme engine that designers or developers [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property MaudernClassicTheme_XML() As String
            Get
                Return ResourceManager.GetString("MaudernClassicTheme_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;UXL_Launcher_Theme&gt;
        '''  &lt;Title&gt;Maudern&lt;/Title&gt;
        '''  &lt;Description&gt;Maudern is a simple, flat theme with a grey color scheme similar in appearance to rock coloration.&lt;/Description&gt;
        '''  &lt;Version&gt;v1.2&lt;/Version&gt;
        '''  &lt;Author&gt;Drew Naylor&lt;/Author&gt;
        '''
        '''  &lt;!-- &quot;UseThemeEngineVersion&quot; is used to specify the version of the
        '''  UXL Launcher Theme Engine to use in case there are changes in newer
        '''  versions of the theme engine that designers or developers don&apos;t want
        '''  to use. Version 1.01 is the oldest version number available [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property MaudernTheme_XML() As String
            Get
                Return ResourceManager.GetString("MaudernTheme_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;UXL_Launcher_Theme&gt;
        '''  &lt;Title&gt;Mitty Theme&lt;/Title&gt;
        '''  &lt;Description&gt;Most of the work for version 3.2 was done while my calico cat, Mitty, was still around, so it felt like a good idea to make this theme for her. I miss her.
        '''    &quot;...if you meant something to someone, if you helped someone, or loved someone, if even a single person remembers you, then maybe you never really die...&quot; - The Machine&lt;/Description&gt;
        '''  &lt;Version&gt;v1.2&lt;/Version&gt;
        '''  &lt;Author&gt;Drew Naylor&lt;/Author&gt;
        '''  
        '''    &lt;!-- &quot;UseThemeEngineVersion&quot; is u [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property MittyTheme_XML() As String
            Get
                Return ResourceManager.GetString("MittyTheme_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property OnenoteLargeSVG_3D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OnenoteLargeSVG_3D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property OneNoteSmallSVG_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OneNoteSmallSVG_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property OutlookLargeSVG_3D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OutlookLargeSVG_3D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property OutlookNewEmailContact() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OutlookNewEmailContact", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property OutlookSmallSVG_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OutlookSmallSVG_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property picture_manager_75x75() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picture_manager_75x75", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PowerpointLargeSVG_3D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PowerpointLargeSVG_3D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PowerPointNewPresentation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PowerPointNewPresentation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PowerpointSmallSVG_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PowerpointSmallSVG_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;UXL_Launcher_Theme&gt;
        '''	  &lt;Title&gt;Pro Dark&lt;/Title&gt;
        '''	  &lt;Description&gt;Dark theme meant to resemble Office 2019&apos;s &quot;Black&quot; theme. The colors may not match exactly as they were eyeballed from the colors used in Word 2019. This theme is not associated with Microsoft, and Microsoft Office is a copyright and trademark/registered trademark of Microsoft Corporation in the United States and other countries.&lt;/Description&gt;
        '''	  &lt;Version&gt;v1.0&lt;/Version&gt;
        '''	  &lt;Author&gt;Drew Naylor&lt;/Author&gt;
        '''
        '''	  &lt;!-- &quot;UseThemeEngineVersion&quot; is u [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property ProDarkTheme_XML() As String
            Get
                Return ResourceManager.GetString("ProDarkTheme_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PublisherLargeSVG_3D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PublisherLargeSVG_3D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PublisherNewPublication() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PublisherNewPublication", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PublisherSmallSVG_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PublisherSmallSVG_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Query_64x64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Query_64x64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;UXL_Launcher_Theme&gt;
        '''  &lt;Title&gt;Return of the Night&lt;/Title&gt;
        '''  &lt;Description&gt;Based on the Test2 theme, &quot;Return of the Night&quot; is a purple theme best suited for those who like proper day/night cycles.&lt;/Description&gt;
        '''  &lt;Version&gt;v1.2&lt;/Version&gt;
        '''  &lt;Author&gt;Drew Naylor&lt;/Author&gt;
        '''
        '''  &lt;!-- &quot;UseThemeEngineVersion&quot; is used to specify the version of the
        '''  UXL Launcher Theme Engine to use in case there are changes in newer
        '''  versions of the theme engine that designers or developers don&apos;t want
        '''  to use. Version 1.01 is  [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property ReturnOfNightTheme_XML() As String
            Get
                Return ResourceManager.GetString("ReturnOfNightTheme_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;UXL_Launcher_Theme&gt;
        '''  &lt;Title&gt;Arr G. Bee&lt;/Title&gt;
        '''  &lt;Description&gt;Arr G. Bee is a theme that&apos;s influenced by the UXL Launcher logo.&lt;/Description&gt;
        '''  &lt;Version&gt;v1.2&lt;/Version&gt;
        '''  &lt;Author&gt;Drew Naylor&lt;/Author&gt;
        '''
        '''  &lt;!-- &quot;UseThemeEngineVersion&quot; is used to specify the version of the
        '''  UXL Launcher Theme Engine to use in case there are changes in newer
        '''  versions of the theme engine that designers or developers don&apos;t want
        '''  to use. Version 1.01 is the oldest version number available and anything
        '''  smaller than  [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property RGBTheme_XML() As String
            Get
                Return ResourceManager.GetString("RGBTheme_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ----------------------------------------------------------------------------------------.
        '''</summary>
        Public ReadOnly Property separator() As String
            Get
                Return ResourceManager.GetString("separator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property SharepointLargeSVG_3D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SharepointLargeSVG_3D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property SharepointSmallSVG_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SharepointSmallSVG_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property small_Language_Settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small_Language_Settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 14,15,16,16nomsi.
        '''</summary>
        Public ReadOnly Property supportedOfficeVersionList() As String
            Get
                Return ResourceManager.GetString("supportedOfficeVersionList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;UXL_Launcher_Theme&gt;
        '''  &lt;Title&gt;Ten Dark&lt;/Title&gt;
        '''  &lt;Description&gt;A dark theme similar to Windows 10&apos;s &quot;Dark Mode&quot;.&lt;/Description&gt;
        '''  &lt;Version&gt;v1.2&lt;/Version&gt;
        '''  &lt;Author&gt;Drew Naylor&lt;/Author&gt;
        '''
        '''  &lt;!-- &quot;UseThemeEngineVersion&quot; is used to specify the version of the
        '''  UXL Launcher Theme Engine to use in case there are changes in newer
        '''  versions of the theme engine that designers or developers don&apos;t want
        '''  to use. Version 1.01 is the oldest version number available and anything
        '''  smaller than that will automati [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property TenDarkTheme_XML() As String
            Get
                Return ResourceManager.GetString("TenDarkTheme_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copyright (C) 2013-2020 Drew Naylor. Licensed under Gnu GPLv3+.
        '''The copyright and license info is the same for the theme engine as it is for UXL Launcher itself as the theme engine is built into the same file as UXL Launcher.
        '''
        '''The UXL Launcher Theme Engine can make the UXL Launcher main window look slightly better and can also use custom themes.
        '''Please be aware that UXL Launcher and the UXL Launcher Theme Engine are both unofficial and not made by Microsoft.
        '''Note that the &quot;License&quot; tab contains only th [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property ThemeEngineInfo_TXT() As String
            Get
                Return ResourceManager.GetString("ThemeEngineInfo_TXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.04.
        '''</summary>
        Public ReadOnly Property themeEngineVersion() As String
            Get
                Return ResourceManager.GetString("themeEngineVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default,Eyesore,Eyesore2,Maudern,MaudernClassic,Mitty,ProDark,ReturnOfNight,RGB,TenDark,(Custom).
        '''</summary>
        Public ReadOnly Property themeList_TXT() As String
            Get
                Return ResourceManager.GetString("themeList_TXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unsafe file extensions blocked from opening in &quot;File&gt;Open...&quot; menu. Source for some of them: https://www.howtogeek.com/137270/50-file-extensions-that-are-potentially-dangerous-on-windows/
        '''.EXE
        '''.PIF
        '''.APPLICATION
        '''.GADGET
        '''.MSI
        '''.MSP
        '''.COM
        '''.SCR
        '''.HTA
        '''.CPL
        '''.MSC
        '''.JAR
        '''.BAT
        '''.CMD
        '''.VBS
        '''.VBE
        '''.JS
        '''.JSE
        '''.WS
        '''.WSF
        '''.WSC
        '''.WSH
        '''.PS1
        '''.PS1XML
        '''.PS2
        '''.PS2XML
        '''.PSC1
        '''.PSC2
        '''.MSH
        '''.MSH1
        '''.MSH2
        '''.MSHXML
        '''.MSH1XML
        '''.MSH2XML
        '''.SCF
        '''.LNK
        '''.INF
        '''.REG
        '''.SWF
        '''.AHK.
        '''</summary>
        Public ReadOnly Property unsafeExtensions_TXT() As String
            Get
                Return ResourceManager.GetString("unsafeExtensions_TXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property uxl_icon_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uxl_icon_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property UXL_Launcher_Banner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UXL_Launcher_Banner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copyright (C) 2013-2020 Drew Naylor. Licensed under Gnu GPLv3+.
        '''
        '''UXL Launcher provides launchers for most Microsoft Office apps in one place.
        '''Please be aware that UXL Launcher is unofficial and not made by Microsoft.
        '''Note that the &quot;License&quot; tab contains only the license for UXL Launcher. Other licenses are linked to from each component&apos;s information area below, if they are different.
        '''
        '''License notice:
        '''UXL Launcher is free software: you can redistribute it and/or modify it under the terms of the GNU Ge [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property UXLLauncherInfo_TXT() As String
            Get
                Return ResourceManager.GetString("UXLLauncherInfo_TXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property WordLargeSVG_3D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WordLargeSVG_3D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property WordNewDocument() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WordNewDocument", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property WordSmallSVG_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WordSmallSVG_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
