'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property alwaysOnTop() As Boolean
            Get
                Return CType(Me("alwaysOnTop"),Boolean)
            End Get
            Set
                Me("alwaysOnTop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C")>  _
        Public Property officeDriveLocation() As String
            Get
                Return CType(Me("officeDriveLocation"),String)
            End Get
            Set
                Me("officeDriveLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property cpuIsSixtyFourBit() As Boolean
            Get
                Return CType(Me("cpuIsSixtyFourBit"),Boolean)
            End Get
            Set
                Me("cpuIsSixtyFourBit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property userHasOfficeThreeSixFive() As Boolean
            Get
                Return CType(Me("userHasOfficeThreeSixFive"),Boolean)
            End Get
            Set
                Me("userHasOfficeThreeSixFive") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("16nomsi")>  _
        Public Property userOfficeVersion() As String
            Get
                Return CType(Me("userOfficeVersion"),String)
            End Get
            Set
                Me("userOfficeVersion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property debugmodeShowLabels() As Boolean
            Get
                Return CType(Me("debugmodeShowLabels"),Boolean)
            End Get
            Set
                Me("debugmodeShowLabels") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Default")>  _
        Public Property userChosenTheme() As String
            Get
                Return CType(Me("userChosenTheme"),String)
            End Get
            Set
                Me("userChosenTheme") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property enableThemeEngine() As Boolean
            Get
                Return CType(Me("enableThemeEngine"),Boolean)
            End Get
            Set
                Me("enableThemeEngine") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property debugmodeShowThemeEngineOutput() As Boolean
            Get
                Return CType(Me("debugmodeShowThemeEngineOutput"),Boolean)
            End Get
            Set
                Me("debugmodeShowThemeEngineOutput") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property hideWhenMinimized() As Boolean
            Get
                Return CType(Me("hideWhenMinimized"),Boolean)
            End Get
            Set
                Me("hideWhenMinimized") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property userCustomThemePath() As String
            Get
                Return CType(Me("userCustomThemePath"),String)
            End Get
            Set
                Me("userCustomThemePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property allowCustomThemes() As Boolean
            Get
                Return CType(Me("allowCustomThemes"),Boolean)
            End Get
            Set
                Me("allowCustomThemes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property userUseCustomStatusbarGreeting() As Boolean
            Get
                Return CType(Me("userUseCustomStatusbarGreeting"),Boolean)
            End Get
            Set
                Me("userUseCustomStatusbarGreeting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property userFirstNameForCustomStatusbarGreeting() As String
            Get
                Return CType(Me("userFirstNameForCustomStatusbarGreeting"),String)
            End Get
            Set
                Me("userFirstNameForCustomStatusbarGreeting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bypassConfiguredLocationForDeprecatedApps() As Boolean
            Get
                Return CType(Me("bypassConfiguredLocationForDeprecatedApps"),Boolean)
            End Get
            Set
                Me("bypassConfiguredLocationForDeprecatedApps") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property showUnsafeFileExtensionBlockedMessage() As Boolean
            Get
                Return CType(Me("showUnsafeFileExtensionBlockedMessage"),Boolean)
            End Get
            Set
                Me("showUnsafeFileExtensionBlockedMessage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property matchWindows10ThemeSettings() As Boolean
            Get
                Return CType(Me("matchWindows10ThemeSettings"),Boolean)
            End Get
            Set
                Me("matchWindows10ThemeSettings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bypassConfiguredLocationForAllApps() As Boolean
            Get
                Return CType(Me("bypassConfiguredLocationForAllApps"),Boolean)
            End Get
            Set
                Me("bypassConfiguredLocationForAllApps") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property autoupgradeUserSettings() As Boolean
            Get
                Return CType(Me("autoupgradeUserSettings"),Boolean)
            End Get
            Set
                Me("autoupgradeUserSettings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ProDark")>  _
        Public Property darkthemeForSystemThemeMatching() As String
            Get
                Return CType(Me("darkthemeForSystemThemeMatching"),String)
            End Get
            Set
                Me("darkthemeForSystemThemeMatching") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.UXL_Launcher.My.MySettings
            Get
                Return Global.UXL_Launcher.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
